<a href="https://twitter.com/share" 
class="twitter-share-button" 
data-url="<?=$strDomain?><?=$strCanonical?>"
data-text="<?=$strPageName?>"
data-lang="en"
data-count="none" 
data-via="<?=$strTwitterName?>" 
data-related="<?=$strTwitterName?>" 
data-counturl="<?=$strDomain?><?=$strCanonical?>" 
rel="nofollow" 
data-dnt="true">Tweet</a>